import random
import time
import os
os.system('cls')
n=random.randrange(2,50,2)
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\nThink Of Any Number")
time.sleep(10)
os.system('cls')
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\nMultiply the number by 2")
time.sleep(10)
os.system('cls')
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\n",n,"\tAdd this number to your number")
time.sleep(10)
os.system('cls')
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\nDivide the number by 2\n")
time.sleep(10)
os.system('cls')
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\nSubtract the Original Number")
time.sleep(10)
os.system('cls')
print("\n\n\n\t\t\t\tLets play the game:")
print("\n\n\nYour Number is ",n/2)
print("Thank You For playing the game")